<a href="https://colab.research.google.com/github/AndreiVergeles2525/PYTHON_LABS/blob/main/lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from time import perf_counter

np.set_printoptions(precision=3, suppress=True)

In [ ]:
def task_1():
    n = int(input())

    t0 = perf_counter()
    a_np = np.zeros((n, n), dtype=int)
    np.fill_diagonal(a_np, np.arange(1, n + 1))
    t_np = perf_counter() - t0

    t0 = perf_counter()
    a_it = np.zeros((n, n), dtype=int)
    for i in range(n):
        a_it[i, i] = i + 1
    t_it = perf_counter() - t0

    print(a_np)
    print(np.allclose(a_np, a_it))
    print(t_np)
    print(t_it)

task_1()

2
[[1 0]
 [0 2]]
True
6.924000001617969e-05
7.036000056359626e-06


In [67]:
def task_3():
    n, m, r, c = map(int, input().split())

    t0 = perf_counter()
    a_np = np.ones((n, m), dtype=int)
    a_np[r - 1::r, :] = 0
    a_np[:, c - 1::c] = 0
    t_np = perf_counter() - t0

    t0 = perf_counter()
    a_it = np.ones((n, m), dtype=int)
    for i in range(n):
        for j in range(m):
            if (i + 1) % r == 0 or (j + 1) % c == 0:
                a_it[i, j] = 0
    t_it = perf_counter() - t0

    print(a_np)
    print(np.allclose(a_np, a_it))
    print(t_np)
    print(t_it)

task_3()

6 7 2 3
[[1 1 0 1 1 0 1]
 [0 0 0 0 0 0 0]
 [1 1 0 1 1 0 1]
 [0 0 0 0 0 0 0]
 [1 1 0 1 1 0 1]
 [0 0 0 0 0 0 0]]
True
0.00016639000023133121
2.5860000278044026e-05


In [ ]:
def task_4():
    n, m = map(int, input().split())

    t0 = perf_counter()
    a_np = np.zeros((n, m), dtype=int)
    a_np[0, :] = np.arange(m)
    t_np = perf_counter() - t0

    t0 = perf_counter()
    a_it = np.zeros((n, m), dtype=int)
    for j in range(m):
        a_it[0, j] = j
    t_it = perf_counter() - t0

    print(a_np)
    print(np.allclose(a_np, a_it))
    print(t_np)
    print(t_it)

task_4()

3 4
[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
True
5.2046000064365217e-05
5.954000016572536e-06


In [ ]:
def task_6():
    v = list(map(int, input().split()))

    t0 = perf_counter()
    a_np = np.array(v, dtype=int)
    a_np[a_np != 0] = -1
    t_np = perf_counter() - t0

    t0 = perf_counter()
    a_it = np.array(v, dtype=int)
    for i in range(len(a_it)):
        if a_it[i] != 0:
            a_it[i] = -1
    t_it = perf_counter() - t0

    print(a_np)
    print(np.allclose(a_np, a_it))
    print(t_np)
    print(t_it)

task_6()

3 4 0 9 7 6 0 4 0 3
[-1 -1  0 -1 -1 -1  0 -1  0 -1]
True
0.00235216400005811
3.9364000031127944e-05


In [ ]:
def task_10():
    n, m = map(int, input().split())

    rng = np.random.default_rng(42)

    t0 = perf_counter()
    a_np = rng.random((n, m))
    mn_np = a_np.min()
    mx_np = a_np.max()
    mean_np = a_np.mean()
    std_np = a_np.std()
    var_np = a_np.var()
    t_np = perf_counter() - t0

    rng = np.random.default_rng(42)
    t0 = perf_counter()
    a_it = rng.random((n, m))
    n1, m1 = a_it.shape
    mn_it = a_it[0, 0]
    mx_it = a_it[0, 0]
    s = 0.0
    total = n1 * m1
    for i in range(n1):
        for j in range(m1):
            x = a_it[i, j]
            s += x
            if x < mn_it:
                mn_it = x
            if x > mx_it:
                mx_it = x
    mean_it = s / total
    var_sum = 0.0
    for i in range(n1):
        for j in range(m1):
            d = a_it[i, j] - mean_it
            var_sum += d * d
    var_it = var_sum / total
    std_it = var_it ** 0.5
    t_it = perf_counter() - t0

    print("мінімум:", round(float(mn_np), 3))
    print("максимум:", round(float(mx_np), 3))
    print("середнє:", round(float(mean_np), 3))
    print("середньоквадратичне відхилення:", round(float(std_np), 3))
    print("дисперсія:", round(float(var_np), 3))
    print(np.allclose([mn_np, mx_np, mean_np, std_np, var_np],
                      [mn_it, mx_it, mean_it, std_it, var_it]))
    print(t_np)
    print(t_it)

task_10()

4 5
мінімум: 0.064
максимум: 0.976
середнє: 0.574
середньоквадратичне відхилення: 0.277
дисперсія: 0.077
True
0.00043962100016869954
3.700400020534289e-05


In [ ]:
def task_12():
    n = int(input())

    t0 = perf_counter()
    a_np = np.ones((n, n), dtype=int)
    a_np[0, :] = 0
    a_np[-1, :] = 0
    a_np[:, 0] = 0
    a_np[:, -1] = 0
    t_np = perf_counter() - t0

    t0 = perf_counter()
    a_it = np.ones((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            if i == 0 or i == n - 1 or j == 0 or j == n - 1:
                a_it[i, j] = 0
    t_it = perf_counter() - t0

    print(a_np)
    print(np.allclose(a_np, a_it))
    print(t_np)
    print(t_it)

task_12()

4
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]
True
6.187500002852175e-05
1.3545999991038116e-05


In [ ]:
def task_16():
    n = int(input())

    t0 = perf_counter()
    a_np = np.zeros((n, n), dtype=int)
    a_np[:, 1::2] = 1
    t_np = perf_counter() - t0

    t0 = perf_counter()
    a_it = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            if j % 2 == 1:
                a_it[i, j] = 1
    t_it = perf_counter() - t0

    print(a_np)
    print(np.allclose(a_np, a_it))
    print(t_np)
    print(t_it)

task_16()

5
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
True
4.21049999204115e-05
9.912999985317583e-06


In [ ]:
def task_18():
    n = int(input())

    t0 = perf_counter()
    a_np = np.arange(n + 1, dtype=int)
    mask = (a_np < n / 2) | (a_np > 3 * n / 4)
    a_np[mask] *= -1
    t_np = perf_counter() - t0

    t0 = perf_counter()
    a_it = np.arange(n + 1, dtype=int)
    for i in range(len(a_it)):
        if a_it[i] < n / 2 or a_it[i] > 3 * n / 4:
            a_it[i] *= -1
    t_it = perf_counter() - t0

    print(a_np)
    print(np.allclose(a_np, a_it))
    print(t_np)
    print(t_it)

task_18()

10
[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]
True
0.0001825589999953081
9.534500009067415e-05


In [ ]:
def task_19():
    n = int(input())

    rng = np.random.default_rng(7)

    t0 = perf_counter()
    a_np = rng.integers(0, 100, size=n)
    u_np = np.unique(a_np).size
    t_np = perf_counter() - t0

    rng = np.random.default_rng(7)
    t0 = perf_counter()
    a_it = rng.integers(0, 100, size=n)
    s = set()
    for x in a_it:
        s.add(int(x))
    u_it = len(s)
    t_it = perf_counter() - t0

    print("У послідовності", a_np, "-", u_np, "унікальних чисел")
    print(u_np == u_it)
    print(t_np)
    print(t_it)

task_19()

30
У послідовності [94 62 68 89 57 77 83 22  5 30 28 87 91  0 49 82 13 79 11 46 81 30 34 27
 71 25 99 44 47 50] - 29 унікальних чисел
True
0.0042922139998609055
7.0208999886745e-05


In [ ]:
#Завдання 2
A = np.array([
    [1, 5, 3, -4],
    [3, 1, -2, 0],
    [5, -7, 0, 10],
    [0, 3, -5, 0]
], dtype=float)

b = np.array([20, 9, -9, 1], dtype=float)

def cramer(A, b):
    detA = np.linalg.det(A)
    n = A.shape[0]
    x = np.zeros(n, dtype=float)
    for i in range(n):
        Ai = A.copy()
        Ai[:, i] = b
        x[i] = np.linalg.det(Ai) / detA
    return x

x_cr = cramer(A, b)
Ax = A @ x_cr
x_inv = np.linalg.inv(A) @ b
x_sol = np.linalg.solve(A, b)

print(x_cr)
print(Ax)
print(x_inv)
print(x_sol)

print(np.allclose(Ax, b))
print(np.allclose(x_cr, x_inv))
print(np.allclose(x_cr, x_sol))
print(np.allclose(x_inv, x_sol))

[ 3.  2.  1. -1.]
[20.  9. -9.  1.]
[ 3.  2.  1. -1.]
[ 3.  2.  1. -1.]
True
True
True
True


In [ ]:
A = np.array([
    [5, 2, 0],
    [10, 4, 1],
    [7, 3, 2]
], dtype=float)

B = np.array([
    [3, 6, -1],
    [-1, -2, 0],
    [2, 1, 3]
], dtype=float)

def expr_np(A, B):
    return (A - B @ B) @ (2 * A + B)

def mat_mul_it(X, Y):
    n, m = X.shape
    m2, k = Y.shape
    R = np.zeros((n, k))
    for i in range(n):
        for j in range(k):
            s = 0.0
            for p in range(m):
                s += X[i, p] * Y[p, j]
            R[i, j] = s
    return R

def mat_add_it(X, Y):
    n, m = X.shape
    R = np.zeros((n, m))
    for i in range(n):
        for j in range(m):
            R[i, j] = X[i, j] + Y[i, j]
    return R

def mat_sub_it(X, Y):
    n, m = X.shape
    R = np.zeros((n, m))
    for i in range(n):
        for j in range(m):
            R[i, j] = X[i, j] - Y[i, j]
    return R

def mat_scalar_it(a, X):
    n, m = X.shape
    R = np.zeros((n, m))
    for i in range(n):
        for j in range(m):
            R[i, j] = a * X[i, j]
    return R

def expr_it(A, B):
    B2 = mat_mul_it(B, B)
    left = mat_sub_it(A, B2)
    right = mat_add_it(mat_scalar_it(2.0, A), B)
    return mat_mul_it(left, right)

t0 = perf_counter()
r_np = expr_np(A, B)
t_np = perf_counter() - t0

t0 = perf_counter()
r_it = expr_it(A, B)
t_it = perf_counter() - t0

print(r_np)
print(r_it)
print(np.allclose(r_np, r_it))
print(t_np)
print(t_it)

[[  91.   64.   32.]
 [ 257.  146.    1.]
 [-322. -135.  -51.]]
[[  91.   64.   32.]
 [ 257.  146.    1.]
 [-322. -135.  -51.]]
True
0.00013896500001919776
0.00013318800006345555
